### ISSUE TITLE
HomeDepot

### ISSUE THREAD

**Issue by mymy59** [rahulisola/BrickseekScraper#3]
Not working with homedepot, can you please check

**Comment by rahulisola** [comment]
This was due to a CloudFlare update to prevent bots / scrapping such as this. I have updated this and seems to be working now.
Cloudflare is expected to continue updating their security measures. If this breaks again due to that, we'll need to update the cloudscraper package. I'll do my best to keep the repo updated if that happens and I see it or am notified of it.
